# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://form.gov.sg/646c01f16e255a00117d65d2")
    self.driver.set_window_size(1454, 926)
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-form-control:nth-child(2) .chakra-radio:nth-child(1) > .chakra-radio__control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-form-control:nth-child(2) .chakra-radio:nth-child(2) > .chakra-radio__control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-form-control:nth-child(2) .chakra-radio:nth-child(3) > .chakra-radio__control").click()
    self.driver.find_element(By.ID, "632824a767747a0011f4468d").click()
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-form-control:nth-child(4) .chakra-radio:nth-child(1) > .chakra-radio__label").click()
    self.driver.find_element(By.ID, "632824a767747a0011f4468d").send_keys("ded")
    self.driver.find_element(By.ID, "632824c3c83c0c0011792d1f").click()
    self.driver.find_element(By.ID, "632824c3c83c0c0011792d1f").send_keys("Yin Chun")
    self.driver.find_element(By.ID, "632824ce8bdc68001194ada8").click()
    self.driver.find_element(By.ID, "632824ce8bdc68001194ada8").send_keys("999")
    self.driver.find_element(By.ID, "632824d6c83c0c0011792f57").click()
    self.driver.find_element(By.ID, "632824d6c83c0c0011792f57").send_keys("999@hotaiil.com")
    self.driver.find_element(By.ID, "632824e18bdc68001194af71").click()
    self.driver.find_element(By.ID, "632824e18bdc68001194af71").send_keys("999.cm")
    self.driver.find_element(By.CSS_SELECTOR, ".css-1szjd8b").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-1szjd8b")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".css-5v0uek").click()
  
